#!/usr/bin/env python3
"""Machine Census reporter: combined drift view + canonical machine context.

Reads every data/hosts/<host>/latest.json (all machines sync theirs through
Synology Drive) and writes data/DRIFT_REPORT.md and data/MACHINE_CONTEXT.md.
Single-host mode degrades gracefully and says it is awaiting the second host.
"""
import glob, json, os, sys
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

AST = ZoneInfo("America/St_Thomas")
HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
STALE_DAYS = 10


def load_hosts():
    hosts = {}
    for p in sorted(glob.glob(os.path.join(DATA, "hosts", "*", "latest.json"))):
        try:
            d = json.load(open(p))
            hosts[d["hostname"]] = d
        except Exception as e:
            print(f"[machine_census] WARN unreadable {p}: {e}", file=sys.stderr)
    return hosts


def row(label, vals, flag_diff=True):
    differ = flag_diff and len(set(vals)) > 1
    mark = "  <-- DIFFERS" if differ else ""
    return f"| {label} | " + " | ".join(str(v).replace("\n", "; ")[:90] for v in vals) + f" |{mark}", differ


def drift_report(hosts):
    names = list(hosts)
    now = datetime.now(AST)
    L = [f"# Machine Census drift report", "",
         f"Generated {now.strftime('%Y-%m-%d %H:%M AST')} on {os.uname().nodename}.", ""]
    if len(hosts) < 2:
        L += ["Only one host snapshot present; awaiting the second machine's census",
              "(it appears automatically once Synology Drive syncs its latest.json).", ""]
    for h, d in hosts.items():
        age = now - datetime.strptime(d["collected_at"][:16], "%Y-%m-%d %H:%M").replace(tzinfo=AST)
        if age > timedelta(days=STALE_DAYS):
            L.append(f"WARNING: {h} snapshot is {age.days} days old; its cron may be broken.")
    L += ["", "| Item | " + " | ".join(names) + " |",
          "|---|" + "---|" * len(names)]
    diffs = 0
    get = lambda fn: [fn(hosts[n]) for n in names]
    for label, fn, flag in [
        ("os", lambda d: d["identity"]["os"], True),
        ("kernel", lambda d: d["identity"]["kernel"], True),
        ("gpu", lambda d: d["gpu"]["cards"], False),
        ("ram", lambda d: d["cpu_ram"]["ram"], False),
        ("apt package count", lambda d: d["packages"]["apt_count"], True),
        ("snap count", lambda d: len(d["packages"]["snaps"]), True),
        ("R", lambda d: d["r"]["version"], True),
        ("system python3", lambda d: d["python"]["system_python3"], True),
        ("conda envs (named)", lambda d: ", ".join(sorted(e for e in d["python"]["conda_envs"] if "/" not in e)) or "none", True),
        ("ollama models", lambda d: d["services_ai"]["ollama_models"], True),
    ]:
        line, differ = row(label, get(fn), flag)
        L.append(line); diffs += differ
    L += ["", "## Major applications", "",
          "| App | " + " | ".join(names) + " |", "|---|" + "---|" * len(names)]
    apps = sorted({a for d in hosts.values() for a in d["apps"]})
    for a in apps:
        line, differ = row(a, [f"{hosts[n]['apps'].get(a, {}).get('version', '?')} @ {hosts[n]['apps'].get(a, {}).get('path', '?')}" for n in names])
        L.append(line); diffs += differ
    if len(hosts) >= 2:
        base, other = names[0], names[1]
        only_base = sorted(set(hosts[base]["packages"]["apt"]) - set(hosts[other]["packages"]["apt"]))
        only_other = sorted(set(hosts[other]["packages"]["apt"]) - set(hosts[base]["packages"]["apt"]))
        L += ["", "## Apt set differences", "",
              f"Only on {base} ({len(only_base)}): {', '.join(only_base[:40])}{' ...' if len(only_base) > 40 else ''}",
              "", f"Only on {other} ({len(only_other)}): {', '.join(only_other[:40])}{' ...' if len(only_other) > 40 else ''}"]
    L += ["", "## VICARIUS desktop integration", "",
          "| Check | " + " | ".join(names) + " |", "|---|" + "---|" * len(names)]
    for label, fn in [("vicarius pinned", lambda d: d["desktop"]["vicarius_pinned"]),
                      ("screensaver pinned", lambda d: d["desktop"]["screensaver_pinned"]),
                      ("aspect-toggle pinned", lambda d: d["desktop"]["aspect_toggle_pinned"]),
                      ("launcher files", lambda d: all(d["desktop"]["launcher_files_present"].values())),
                      ("gnome extension", lambda d: d["desktop"]["vicarius_extension_present"])]:
        line, differ = row(label, get(fn))
        L.append(line); diffs += differ
    L += ["", f"Total flagged differences: {diffs}", ""]
    return "\n".join(L)


def machine_context(hosts):
    names = list(hosts)
    now = datetime.now(AST)
    L = ["# MACHINE_CONTEXT (generated by machine_census; do not hand-edit)", "",
         f"Refreshed {now.strftime('%Y-%m-%d %H:%M AST')}. VICARIUS runs on "
         f"{len(hosts)} machine(s): {', '.join(names)}. They are one merged platform:",
         "every module must run on ALL of them or say why not in its README.", "",
         "## Rules for agents (installing or authoring modules)", ""]
    conv = next(iter(hosts.values()))["conventions"]
    for k, v in conv.items():
        L.append(f"- {k.replace('_', ' ')}: {v}")
    L += ["- Before prescribing an install, check the per-host facts below and the",
          "  full snapshots at modules/machine_census/github_repo/data/hosts/<host>/latest.json.",
          "- Validate a module's needs on both machines: run",
          "  `python3 modules/machine_census/github_repo/check_module_compat.py <module_dir>`.", ""]
    for h in names:
        d = hosts[h]
        L += [f"## {h}", "",
              f"- {d['identity']['os']}, kernel {d['identity']['kernel']}, {d['identity']['model']}",
              f"- CPU: {d['cpu_ram']['cpu']} ({d['cpu_ram']['threads']} threads), RAM {d['cpu_ram']['ram']}",
              f"- GPU: {d['gpu']['cards']}",
              f"- Mounts: {d['storage']['mounts']}".replace("\n", "; "),
              f"- Metashape: {d['apps']['metashape']['version']} at {d['apps']['metashape']['path']}",
              f"- Ollama models: {d['services_ai']['ollama_models']}".replace("\n", "; "), ""]
    return "\n".join(L)


def main():
    hosts = load_hosts()
    if not hosts:
        print("[machine_census] no snapshots found; run collect.py first", file=sys.stderr)
        return 1
    open(os.path.join(DATA, "DRIFT_REPORT.md"), "w").write(drift_report(hosts))
    open(os.path.join(DATA, "MACHINE_CONTEXT.md"), "w").write(machine_context(hosts))
    print(f"[machine_census] report over {len(hosts)} host(s): {', '.join(hosts)} -> data/DRIFT_REPORT.md, data/MACHINE_CONTEXT.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
